### ISSUE TITLE
Allow colortable parameter for Geo/Geo3D plots to be an (r,g,b) or (r,g,b,a) list instead of only (x,r,g,b,a)

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/atmosphere-virtual-lab#2]
The alpha should be set to 1.0 if not provided.
The 'x' can be set by using linear interpolation. e.g. in python: `[[i] + c for i, c in zip(np.linspace(0, 1, len(colors), True), colors)]`

**Comment by srepmub** [comment]
implemented on the python side.

note that True is the default for np.linspace(endpoint), so I don't pass it. 

second note is that we now build a low-level VTK lut, where there probably exists higher-level VTK functionality (I keep all such things as TODO's in the code).

the javascript side probably wants to accept (r,g,b) and (r,g,b,a) format as well.. otherwise we can 'pre-process' the colormap before passing.
